### ISSUE TITLE
Investigate implementation of RTS/CTS attack

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#9]
The paper covers the ability to use RTS/CTS to retrieve(maybe confirm?) the global MAC address. More research has to be done by reading the main paper and the one it references.

**Comment by Timru** [comment]
Hey,

were you able ot reproduce the RTS/CTS attack? I wrote my master thesis on this topic but found it to be unusable as devices will only respond to RTS upon sending out probe requests...

**Comment by denizaydemir** [comment]
The purpose of RTS/CTS attack is not to retrieve the MAC address of a device. It's to detect a device whether the device exists in the surroundings of the RTS sender.
I was able to receive CTS signals when I sent RTS to priorly known MAC adresses.

**Comment by Timru** [comment]
I know how the attack works and implemented it myself, too. The problem is that a device will respond to RTS messages targetting the global MAC only if it wakes its radio NIC to send a probe request. In that case we can see the global device MAC anyway through the probe request which makes the Attack in my opinion kind of useless. Also they stated that they were able to"..elicit a specific response from them at any time if they are within wireless range..". So my question is: where you able to elicit a response (CTS) any time you send a RTS message?
